import type { Lang, Config, Park, MeetingPoint, Task } from "./types"

export const FLOWER_BG =
  "https://images.unsplash.com/photo-1717683822568-3b85cb0b2844?w=700&h=500&fit=crop&auto=format"

export const INITIAL_CONFIG: Config = {
  name: "Fotos Instantáneas",
  instagram: "@fotosinstantaneas.cl",
  price1: "$3.000",
  price2: "2 × $5.000",
  tagline: {
    es: "¡Llévate tu recuerdo al instante!",
    en: "Take your memory home instantly!",
    pt: "Leve sua memória na hora!",
  },
  price1lbl: { es: "1 foto", en: "1 photo", pt: "1 foto" },
  price2lbl: { es: "2 fotos", en: "2 photos", pt: "2 fotos" },
  payment: {
    es: "Efectivo / transferencia",
    en: "Cash / transfer",
    pt: "Dinheiro / transferência",
  },
}

export const DEFAULT_PARKS: Park[] = [
  { id: "forestal", names: { es: "Parque Forestal", en: "Parque Forestal", pt: "Parque Forestal" }, area: "Santiago Centro", emoji: "🌳", lat: -33.4372, lng: -70.644 },
  { id: "lastarrias", names: { es: "Barrio Lastarrias", en: "Lastarrias", pt: "Lastarrias" }, area: "Providencia", emoji: "☕", lat: -33.4395, lng: -70.6392 },
  { id: "sancristobal", names: { es: "Cerro San Cristóbal", en: "San Cristóbal Hill", pt: "Cerro San Cristóbal" }, area: "Providencia / Recoleta", emoji: "⛰️", lat: -33.4233, lng: -70.6335 },
  { id: "bicentenario", names: { es: "Parque Bicentenario", en: "Bicentennial Park", pt: "Parque Bicentenário" }, area: "Vitacura", emoji: "🌿", lat: -33.405, lng: -70.598 },
  { id: "bustamante", names: { es: "Parque Bustamante", en: "Bustamante Park", pt: "Parque Bustamante" }, area: "Providencia", emoji: "🏞️", lat: -33.447, lng: -70.635 },
  { id: "baquedano", names: { es: "Plaza Baquedano", en: "Baquedano Square", pt: "Praça Baquedano" }, area: "Santiago Centro", emoji: "🗺️", lat: -33.438, lng: -70.6373 },
]

export const DEFAULT_MEETING_POINTS: MeetingPoint[] = [
  { id: "mp1", names: { es: "Puente Pío Nono", en: "Pío Nono Bridge", pt: "Ponte Pío Nono" }, parkId: "forestal", lat: -33.4355, lng: -70.6428, active: true },
  { id: "mp2", names: { es: "Bandejón central Forestal", en: "Forestal Central Path", pt: "Caminho Central Forestal" }, parkId: "forestal", lat: -33.4378, lng: -70.6415, active: true },
  { id: "mp3", names: { es: "Plaza Mulato Gil", en: "Mulato Gil Square", pt: "Praça Mulato Gil" }, parkId: "lastarrias", lat: -33.4398, lng: -70.6384, active: true },
  { id: "mp4", names: { es: "Entrada Bellavista (Funicular)", en: "Bellavista Entrance", pt: "Entrada Bellavista" }, parkId: "sancristobal", lat: -33.4289, lng: -70.6341, active: true },
  { id: "mp5", names: { es: "Entrada Parque Bustamante", en: "Bustamante Entrance", pt: "Entrada Bustamante" }, parkId: "bustamante", lat: -33.4468, lng: -70.6354, active: true },
  { id: "mp6", names: { es: "Glorieta Plaza Baquedano", en: "Baquedano Rotunda", pt: "Glorieta Baquedano" }, parkId: "baquedano", lat: -33.4383, lng: -70.6368, active: false },
]

export const DEFAULT_TASKS: Task[] = [
  { id: "t1", title: { es: "Llegar al punto de encuentro", en: "Arrive at meeting point", pt: "Chegar ao ponto de encontro" }, points: 20, category: "ops", done: false },
  { id: "t2", title: { es: "Preparar la cámara", en: "Set up the camera", pt: "Preparar a câmera" }, points: 15, category: "ops", done: false },
  { id: "t3", title: { es: "Primera venta del día 🎉", en: "First sale of the day 🎉", pt: "Primeira venda do dia 🎉" }, points: 30, category: "ops", done: false },
  { id: "t4", title: { es: "Compartir flyer en Instagram", en: "Share flyer on Instagram", pt: "Compartilhar flyer no Instagram" }, points: 25, category: "extra", done: false },
  { id: "t5", title: { es: "Beber agua 💧", en: "Drink water 💧", pt: "Beber água 💧" }, points: 10, category: "care", done: false },
  { id: "t6", title: { es: "Tomar un descanso de 5 min", en: "Take a 5-min break", pt: "Fazer uma pausa de 5 min" }, points: 10, category: "care", done: false },
  { id: "t7", title: { es: "Saludar a alguien nuevo", en: "Greet someone new", pt: "Cumprimentar alguém novo" }, points: 20, category: "comms", done: false },
  { id: "t8", title: { es: "Terminar la sesión del día", en: "Close the day's session", pt: "Encerrar a sessão do dia" }, points: 25, category: "ops", done: false },
]

export const LEVELS = [
  { min: 0, max: 99, name: "Caracol Curioso", icon: "🐌" },
  { min: 100, max: 299, name: "Arcoíris", icon: "🌈" },
  { min: 300, max: 599, name: "Estrellita", icon: "⭐" },
  { min: 600, max: 999, name: "Arcoíris Brillante", icon: "🌈⭐" },
  { min: 1000, max: 1999, name: "Caracol Mágico", icon: "🐌✨" },
  { min: 2000, max: Infinity, name: "Universo Camila", icon: "🌈⭐🐌" },
]

export function getLevel(points: number) {
  return LEVELS.find((l) => points >= l.min && points <= l.max) ?? LEVELS[0]
}

export const STAR = "⭐"

export const CATEGORY_META = {
  ops: { icon: "🎯", color: "#2563eb", bg: "#eff6ff", label: { es: "Operacional", en: "Operational", pt: "Operacional" } },
  comms: { icon: "💬", color: "#7c3aed", bg: "#f5f3ff", label: { es: "Comunicación", en: "Communication", pt: "Comunicação" } },
  care: { icon: "🌱", color: "#16a34a", bg: "#f0fdf4", label: { es: "Autocuidado", en: "Self-care", pt: "Autocuidado" } },
  extra: { icon: "⭐", color: "#d97706", bg: "#fffbeb", label: { es: "Extra", en: "Extra", pt: "Extra" } },
} as const

export const TR = {
  es: {
    tabs: { flyer: "Flyer", edit: "Editar", map: "Mapa", roi: "ROI", apoyo: "Apoyo", historial: "Historial" },
    heroTitle: "FOTOS\nINSTANTÁNEAS",
    download: "⬇  Descargar Flyer",
    downloading: "Descargando...",
    rulesTitle: "Reglas básicas",
    rules: [["📸", "Pago adelantado"], ["🚫", "Sin devoluciones"], ["⏱️", "Espera ~2 min"], ["🙂", "Una persona a la vez"]] as [string, string][],
    contactSub: "¿Preguntas? Escríbeme",
    editTitle: "Variables del flyer",
    fieldName: "Nombre / Negocio", fieldInsta: "Instagram", fieldPrice1: "Precio 1", fieldPrice2: "Precio 2",
    meetingTitle: "Puntos de encuentro", meetingActive: "activo", meetingInactive: "inactivo",
    addLocation: "Agregar lugar", addLocationTitle: "Nuevo lugar", save: "Guardar", cancel: "Cancelar",
    fieldEmoji: "Emoji", fieldNameEs: "Nombre ES", fieldNameEn: "Nombre EN", fieldNamePt: "Nombre PT",
    fieldArea: "Sector / Comuna", fieldLat: "Latitud", fieldLng: "Longitud",
    mapTitle: "Mis lugares habituales", mapSub: "Toca un pin para seleccionar",
    clearPark: "Limpiar", conqueredParks: "Lugares conquistados", visitAll: "¡Visita todos para bonus!",
    roiTitle: "Registro de ventas", roiToday: "Sesión actual", roiAdd1: "+ 1 foto", roiAdd2: "+ 2 fotos",
    roiUndo: "Deshacer", roiTotal: "Total ganado", roiPhotos: "Fotos", roiSessions: "Sesiones",
    roiAvg: "Promedio/sesión", roiNotes: "Notas", roiSave: "Guardar sesión", roiHistory: "Sesiones guardadas", roiEmpty: "Sin sesiones",
    apoyoTitle: "Mi espacio Camila",
    checkinTitle: "¿Cómo estás hoy?",
    energyLabel: "Energía",
    mutismLabel: "Nivel de voz hoy",
    mutismHigh: "Sin voz", mutismMed: "Poca voz", mutismLow: "Con voz",
    mutismNote: { high: "Día silencioso — usa las tarjetas de comunicación abajo 👇", medium: "Día intermedio — ve a tu ritmo", low: "Día verbal — ¡aprovecha!" },
    checkinSave: "Registrar estado",
    commTitle: "Tarjetas para clientes",
    commSub: "Toca cualquier tarjeta para mostrarla en pantalla completa",
    commCards: [
      { id: "greet", emoji: "👋", text: "¡Hola! ¿Cuántas fotos quieres?\n1 foto o 2 fotos", sub: "Señala con los dedos" },
      { id: "price", emoji: "💰", text: "$3.000 = 1 foto\n$5.000 = 2 fotos", sub: "Pago antes de la foto" },
      { id: "pay", emoji: "💳", text: "Efectivo o\ntransferencia", sub: "¡Pago primero por favor!" },
      { id: "wait", emoji: "⏱️", text: "¡Listo! Espera\n~2 minutos", sub: "Tu foto está imprimiéndose" },
      { id: "done", emoji: "🎉", text: "¡Aquí está\ntu foto!", sub: "¡Gracias por comprar! ♡" },
    ] as { id: string; emoji: string; text: string; sub: string }[],
    tasksTitle: "Tareas del día",
    addTask: "Nueva tarea",
    taskPoints: "⭐",
    pointsTotal: "Mis estrellitas",
    levelLabel: "Nivel",
    historialTitle: "Historial de operaciones",
    historialEmpty: "Sin registros aún",
    historialFilter: "Filtrar",
    filterAll: "Todo", filterRoi: "Ventas", filterCheckin: "Check-ins", filterTasks: "Tareas", filterFlyer: "Flyers",
    kindLabel: { roi: "Sesión de ventas", checkin: "Check-in del día", download: "Flyer descargado", task: "Tarea completada" },
    editEntry: "Editar", deleteEntry: "Eliminar", noLocation: "Sin ubicación",
  },
  en: {
    tabs: { flyer: "Flyer", edit: "Edit", map: "Map", roi: "ROI", apoyo: "Support", historial: "History" },
    heroTitle: "INSTANT\nPHOTOS",
    download: "⬇  Download Flyer", downloading: "Downloading...",
    rulesTitle: "Basic rules",
    rules: [["📸", "Pay in advance"], ["🚫", "No refunds"], ["⏱️", "Wait ~2 min"], ["🙂", "One at a time"]] as [string, string][],
    contactSub: "Questions? Message me",
    editTitle: "Flyer variables",
    fieldName: "Name / Business", fieldInsta: "Instagram", fieldPrice1: "Price 1", fieldPrice2: "Price 2",
    meetingTitle: "Meeting points", meetingActive: "active", meetingInactive: "inactive",
    addLocation: "Add location", addLocationTitle: "New location", save: "Save", cancel: "Cancel",
    fieldEmoji: "Emoji", fieldNameEs: "Name ES", fieldNameEn: "Name EN", fieldNamePt: "Name PT",
    fieldArea: "Area", fieldLat: "Latitude", fieldLng: "Longitude",
    mapTitle: "My usual spots", mapSub: "Tap a pin to select",
    clearPark: "Clear", conqueredParks: "Conquered spots", visitAll: "Visit all for a bonus!",
    roiTitle: "Sales tracker", roiToday: "Current session", roiAdd1: "+ 1 photo", roiAdd2: "+ 2 photos",
    roiUndo: "Undo", roiTotal: "Total earned", roiPhotos: "Photos", roiSessions: "Sessions",
    roiAvg: "Avg/session", roiNotes: "Notes", roiSave: "Save session", roiHistory: "Saved sessions", roiEmpty: "No sessions",
    apoyoTitle: "My space — Camila",
    checkinTitle: "How are you today?",
    energyLabel: "Energy",
    mutismLabel: "Voice level today",
    mutismHigh: "No voice", mutismMed: "Some voice", mutismLow: "Full voice",
    mutismNote: { high: "Quiet day — use the communication cards below 👇", medium: "Middle day — go at your pace", low: "Verbal day — make the most of it!" },
    checkinSave: "Save check-in",
    commTitle: "Cards for clients",
    commSub: "Tap any card to show it fullscreen",
    commCards: [
      { id: "greet", emoji: "👋", text: "Hi! How many photos?\n1 photo or 2 photos", sub: "Point with your fingers" },
      { id: "price", emoji: "💰", text: "$3.000 = 1 photo\n$5.000 = 2 photos", sub: "Pay before the photo" },
      { id: "pay", emoji: "💳", text: "Cash or\ntransfer", sub: "Payment first please!" },
      { id: "wait", emoji: "⏱️", text: "Done! Wait\n~2 minutes", sub: "Your photo is printing" },
      { id: "done", emoji: "🎉", text: "Here's\nyour photo!", sub: "Thank you! ♡" },
    ] as { id: string; emoji: string; text: string; sub: string }[],
    tasksTitle: "Today's tasks",
    addTask: "New task",
    taskPoints: "⭐",
    pointsTotal: "My stars",
    levelLabel: "Level",
    historialTitle: "Operations history",
    historialEmpty: "No records yet",
    historialFilter: "Filter",
    filterAll: "All", filterRoi: "Sales", filterCheckin: "Check-ins", filterTasks: "Tasks", filterFlyer: "Flyers",
    kindLabel: { roi: "Sales session", checkin: "Daily check-in", download: "Flyer downloaded", task: "Task completed" },
    editEntry: "Edit", deleteEntry: "Delete", noLocation: "No location",
  },
  pt: {
    tabs: { flyer: "Flyer", edit: "Editar", map: "Mapa", roi: "ROI", apoyo: "Apoio", historial: "Histórico" },
    heroTitle: "FOTOS\nINSTANTÂNEAS",
    download: "⬇  Baixar Flyer", downloading: "Baixando...",
    rulesTitle: "Regras básicas",
    rules: [["📸", "Pague adiantado"], ["🚫", "Sem reembolsos"], ["⏱️", "Aguarde ~2 min"], ["🙂", "Uma por vez"]] as [string, string][],
    contactSub: "Dúvidas? Me escreva",
    editTitle: "Variáveis do flyer",
    fieldName: "Nome / Negócio", fieldInsta: "Instagram", fieldPrice1: "Preço 1", fieldPrice2: "Preço 2",
    meetingTitle: "Pontos de encontro", meetingActive: "ativo", meetingInactive: "inativo",
    addLocation: "Adicionar local", addLocationTitle: "Novo local", save: "Salvar", cancel: "Cancelar",
    fieldEmoji: "Emoji", fieldNameEs: "Nome ES", fieldNameEn: "Nome EN", fieldNamePt: "Nome PT",
    fieldArea: "Área / Bairro", fieldLat: "Latitude", fieldLng: "Longitude",
    mapTitle: "Meus locais habituais", mapSub: "Toque em um pin para selecionar",
    clearPark: "Limpar", conqueredParks: "Locais conquistados", visitAll: "Visite todos para bônus!",
    roiTitle: "Registro de vendas", roiToday: "Sessão atual", roiAdd1: "+ 1 foto", roiAdd2: "+ 2 fotos",
    roiUndo: "Desfazer", roiTotal: "Total ganho", roiPhotos: "Fotos", roiSessions: "Sessões",
    roiAvg: "Média/sessão", roiNotes: "Notas", roiSave: "Salvar sessão", roiHistory: "Sessões salvas", roiEmpty: "Sem sessões",
    apoyoTitle: "Meu espaço — Camila",
    checkinTitle: "Como você está hoje?",
    energyLabel: "Energia",
    mutismLabel: "Nível de voz hoje",
    mutismHigh: "Sem voz", mutismMed: "Pouca voz", mutismLow: "Com voz",
    mutismNote: { high: "Dia silencioso — use os cartões abaixo 👇", medium: "Dia intermediário — vá no seu ritmo", low: "Dia verbal — aproveite!" },
    checkinSave: "Registrar estado",
    commTitle: "Cartões para clientes",
    commSub: "Toque em qualquer cartão para tela cheia",
    commCards: [
      { id: "greet", emoji: "👋", text: "Olá! Quantas fotos?\n1 foto ou 2 fotos", sub: "Aponte com os dedos" },
      { id: "price", emoji: "💰", text: "$3.000 = 1 foto\n$5.000 = 2 fotos", sub: "Pague antes da foto" },
      { id: "pay", emoji: "💳", text: "Dinheiro ou\ntransferência", sub: "Pagamento primeiro!" },
      { id: "wait", emoji: "⏱️", text: "Pronto! Aguarde\n~2 minutos", sub: "Sua foto está imprimindo" },
      { id: "done", emoji: "🎉", text: "Aqui está\nsua foto!", sub: "Obrigada! ♡" },
    ] as { id: string; emoji: string; text: string; sub: string }[],
    tasksTitle: "Tarefas do dia",
    addTask: "Nova tarefa",
    taskPoints: "⭐",
    pointsTotal: "Minhas estrelinhas",
    levelLabel: "Nível",
    historialTitle: "Histórico de operações",
    historialEmpty: "Sem registros ainda",
    historialFilter: "Filtrar",
    filterAll: "Tudo", filterRoi: "Vendas", filterCheckin: "Check-ins", filterTasks: "Tarefas", filterFlyer: "Flyers",
    kindLabel: { roi: "Sessão de vendas", checkin: "Check-in do dia", download: "Flyer baixado", task: "Tarefa concluída" },
    editEntry: "Editar", deleteEntry: "Excluir", noLocation: "Sem local",
  },
} as const
